<?php

namespace App\Http\Controllers;

use Tests\TestCase;

class EmpresaControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/empresa/adicionar',
            [
                "cnpj" => "54104595000154",
                "nome" => "empresa1",
                "endereco" => "rua x",
                "telefone" => "1234567890",
                "encargo" => "encargo"
            ]
        );

        $response
            ->assertStatus(200);
    }
}
