<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use Tests\TestCase;

class EmpresaControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/empresa/adicionar',
            [
                "cnpj" => rand(10000000000000, 99999999999999),
                "nome" => Str::random(10),
                "endereco" => "Rua " . Str::random(5).Str::random(10),
                "telefone" => rand(100000000, 999999999),
                "encargo" => Str::random(10)
            ]
        );

        $response
            ->assertStatus(200);
    }
}
