<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use Tests\TestCase;

class ProdutoControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/produto/adicionar',
            [
                "ncm" => rand(10000000, 99999999),
                "nome" => Str::random(10),
                "quantidade" => rand(1, 10000),
                "valor" => rand(1, 10000)
            ]
        );

        $response
            ->assertStatus(200);
    }

}
