<?php

namespace App\Http\Controllers;

use Tests\TestCase;

class ProdutoControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/produto/adicionar',
            [
                "ncm" => "12345678",
                "nome" => "teste2",
                "quantidade" => "1",
                "valor" => "123"
            ]
        );

        $response
            ->assertStatus(200);
    }

}
