<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Produto;
use App\Http\Controllers\ProdutoController;
use routes\api;

class ProdutoTeste extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withExceptionHandling();
    }
    /**
     * A basic unit test example.
     *
     * @return void
     */
    
    public function testAddProduto()
    {
        $response = $this->postJson('/api/produto/adicionar', ['nome' => 'mascara', 'valor' => '24.50', 'quantidade' => '1']);

        $response
            ->assertStatus(201)
            ->assertExactJson([
                'correct' => true,
            ]);
 
    }
}
