<?php

namespace App\Http\Controllers;

use Tests\TestCase;

class TransacaoControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/transacao/adicionar',
            [
                "empresa" => "1",
                "produto" => "1",
                "quantidade" => "123",
                "data" => "2020-04-03",
                "valor" => "10000",
                "condicao" => "condicao"
            ]
        );

        $response
            ->assertStatus(200);
    }
}
