<?php

namespace App\Http\Controllers;

use Illuminate\Support\Str;
use Tests\TestCase;

class UsuarioControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAdd()
    {
        $response = $this->postJson('/api/usuario/adicionar',
            [
                "email" => Str::random(10).'@gmail.com',
                "senha" => "123",
            ]
        );

        $response
            ->assertStatus(200);
    }
}
